name: First_Workflow
on: 
  push:
    branches:
      - Main
jobs:
  first_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo :"Hello,world!"
          echo :"Hello Againn"