name: Manual_Workflow
on:
    workflow_dispatch:
jobs:
  Manual_first_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First manual step
        run: |
          echo "Hello,world!"
          echo "Helloo Again"