name: cronjob_Workflow
on: 
  schedule:
    - cron: '*/1 * * * *' #run in every one minutes
jobs:
  Cron_first_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron workflow
        run: |
          echo "Hello,world!"
          echo "Hello Again"