name: Multi_Workflow

on: 
  push:
    branches:
      - main  # make sure this matches your branch name

jobs:
  first_workflow_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "first_workflow_job"
          
  second_workflow_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Second step
        run: |
          echo "second workflow job"
