name: Dependent_Multi_Workflow

on: 
  workflow_dispatch:


jobs:
  Dependent_first_workflow_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "first workflow job"
          
  Dependent_second_workflow_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: |
          echo "second workflow job"
  
  Dependent_Third_workflow_jobs:
    runs-on: ubuntu-latest
    needs: [Dependent_first_workflow_jobs,Dependent_second_workflow_jobs]
    steps:
      - name: Third step
        run: |
          echo "Third workflow job"

          runs

