name: Dependent_conditional_Workflow

on: 
  push:
    paths:
      - "backend/**"
    branches:
      - main
      
jobs:
  conditional_workflow_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build backend image
        run: |
          echo "backend image is building"
