name: Dependent_conditional_Workflows

on: 
  push:
    paths:
      - "backend/**"
    branches:
    - main
      
jobs:
 conditional_workflow_jobs:
    runs-on: ubuntu-latest
    needs:
    steps:
      - name: Build backend image
        run: |
          echo "backend image is building"
          
 