name: Condition_Workflow

on:
  push:
    paths:
      - "backend/**"


    
jobs:
  Dependent_first_workflow_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Build Backend Image
        run: echo "Backend image is building"
          
  