name: Dependent_conditional_Workflow

on: 
  push:
    paths:
      - "backend/**"
   
      
jobs:
  conditional_workflow_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build backend image
        run: echo "bbbackend image is building"
