name: Value Pass Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Unnamed"

jobs:
  get-value-workflow-job:
    runs-on: ubuntu-latest

    outputs:
      message: ${{ steps.setmsg.outputs.message }}

    steps:
      - name: Generate Greeting Message
        id: setmsg
        run: |
          echo "message=Hello, ${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT

  print-value-workflow-job:
    runs-on: ubuntu-latest
    needs: get-value-workflow-job

    steps:
      - name: Print Greeting Message
        run: |
          echo "${{ needs.get-value-workflow-job.outputs.message }}"
