name: Pre-define-workflow

on:
  workflow_dispatch:

jobs:
  predefine_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: NodeJs Version
        run: node -v
        
      - name: Setup NodeJs
        uses: action/setup-node@v4
        with:
            node-version : '20'
