name: Pre-define-workflow

on:
  workflow_dispatch:

jobs:
  predefine_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: NodeJs Version Before Setup
        run: node -v || echo "Node not installed yet"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: NodeJs Version After Setup
        run: node -v
